_pastel_config_background_jobs() {
    typeset -g POWERLEVEL9K_BACKGROUND_JOBS_ICON=""
    typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="none"
}

_pastel_config_battery() {
    # TODO: Investigate more into this
    typeset -g POWERLEVEL9K_BATTERY_LEVEL_BACKGROUND=(none none none none none none none none none none none)
}

_pastel_config_chruby() {
    # TODO: Install chruby to test theming
    typeset -g POWERLEVEL9K_CHRUBY_BACKGROUND="none"
}

_pastel_config_command_execution_time() {
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="$__PASTEL_COLORS[yellow]"
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="none"
}

_pastel_config_context() {
    typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND="none"
}

_pastel_config_date() {
    typeset -g POWERLEVEL9K_DATE_FOREGROUND="$__PASTEL_COLORS[grey]"
    typeset -g POWERLEVEL9K_DATE_BACKGROUND="none"
}

_pastel_config_dir() {
    typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=true

    typeset -g POWERLEVEL9K_SHORTEN_DELIMITER="..."
    typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=7

    typeset -g POWERLEVEL9K_FOLDER_ICON=""
    typeset -g POWERLEVEL9K_HOME_ICON=""
    typeset -g POWERLEVEL9K_HOME_SUB_ICON=""
    typeset -g POWERLEVEL9K_ETC_ICON=""
    typeset -g POWERLEVEL9K_LOCK_ICON=""

    typeset -g POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="$__PASTEL_COLORS[purple]"
    typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND="$__PASTEL_COLORS[blue]"
    typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="$POWERLEVEL9K_DIR_HOME_FOREGROUND"
    typeset -g POWERLEVEL9K_DIR_ETC_FOREGROUND="$__PASTEL_COLORS[purple]"
    typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND="$__PASTEL_COLORS[red]"
    typeset -g POWERLEVEL9K_DIR_{DEFAULT,HOME,HOME_SUBFOLDER,ETC,NOT_WRITABLE}_BACKGROUND="none"
}

_pastel_config_disk_usage() {
    # TODO: Background wont go away. Investivate further
    typeset -g POWERLEVEL9K_DISK_USAGE_BACKGROUND="none"
}

_pastel_config_host() {
    typeset -g POWERLEVEL9K_HOST_BACKGROUND="none"
}

_pastel_config_ip() {
    typeset -g POWERLEVEL9K_IP_FOREGROUND="$__PASTEL_COLORS[grey]"
    typeset -g POWERLEVEL9K_IP_BACKGROUND="none"
}

_pastel_config_vpn_ip() {
    typeset -g POWERLEVEL9K_VPN_IP_FOREGROUND="$__PASTEL_COLORS[grey]"
    typeset -g POWERLEVEL9K_VPN_IP_BACKGROUND="none"
}

_pastel_config_public_ip() {
    typeset -g POWERLEVEL9K_PUBLIC_IP_FOREGROUND="$__PASTEL_COLORS[grey]"
    typeset -g POWERLEVEL9K_PUBLIC_IP_BACKGROUND="none"
}

_pastel_config_load() {
    # TODO: Background wont go away. Investivate further
    typeset -g POWERLEVEL9K_LOAD_BACKGROUND="none"
}

_pastel_config_nodeenv() {
    typeset -g POWERLEVEL9K_NODEENV_BACKGROUND="none"
}

_pastel_config_prompt_char() {
    typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND="$__PASTEL_COLORS[blue]"
    typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND="$__PASTEL_COLORS[red]"
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION="$PASTEL_PROMPT_CHAR"
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION="$PASTEL_PROMPT_CHAR_INV"
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION="V"
    typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=""
}

_pastel_config_rbenv() {
    typeset -g POWERLEVEL9K_RBENV_BACKGROUND="none"
}

_pastel_config_pyenv() {
    typeset -g POWERLEVEL9K_PYENV_FOREGROUND="$__PASTEL_COLORS[yellow]"
    typeset -g POWERLEVEL9K_PYENV_BACKGROUND="none"
}

_pastel_config_rspec_stats() {
    typeset -g POWERLEVEL9K_RSPEC_STATS_BACKGROUND="none"
}

_pastel_config_status() {
    typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND="$__PASTEL_COLORS[green]"
    typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND="$__PASTEL_COLORS[red]"
    typeset -g POWERLEVEL9K_STATUS_{OK,ERROR}_BACKGROUND="none"
    
    typeset -g POWERLEVEL9K_CARRIAGE_RETURN_ICON=
    
    typeset -g POWERLEVEL9K_STATUS_OK=false
} 

_pastel_config_ram() {
    typeset -g POWERLEVEL9K_RAM_FOREGROUND="$__PASTEL_COLORS[yellow]"
    typeset -g POWERLEVEL9K_RAM_BACKGROUND="none"
}

_pastel_config_symfony2_tests() {
    typeset -g POWERLEVEL9K_SYMFONY2_TESTS_BACKGROUND="none"
}

_pastel_config_time() {
    typeset -g POWERLEVEL9K_TIME_FOREGROUND="$__PASTEL_COLORS[grey]"
    typeset -g POWERLEVEL9K_TIME_BACKGROUND="none"
}

_pastel_config_user() {
    typeset -g POWERLEVEL9K_USER_{DEFAULT,SUDO,ROOT}_BACKGROUND="none"
}

_pastel_config_vcs_p9k() {
    typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON="%F{$POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND}?%f"
    typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON="%F{$POWERLEVEL9K_VCS_MODIFIED_FOREGROUND}!%f"
    typeset -g POWERLEVEL9K_VCS_STAGED_ICON="%F{$__PASTEL_COLORS[green]}+%f"
    typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON="%F{$POWERLEVEL9K_VCS_CLEAN_FOREGROUND}>%f"
    typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON="%F{$POWERLEVEL9K_VCS_CLEAN_FOREGROUND}<%f"
    typeset -g POWERLEVEL9K_VCS_STASH_ICON="%F{$POWERLEVEL9K_VCS_CLEAN_FOREGROUND}*%f"
}

_pastel_config_vcs_p10k() {
    typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNTRACKEDFORMAT_FOREGROUND="$POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND"
    typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNSTAGEDFORMAT_FOREGROUND="$POWERLEVEL9K_VCS_MODIFIED_FOREGROUND"
    typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STAGEDFORMAT_FOREGROUND="$__PASTEL_COLORS[green]"
    typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_INCOMING_CHANGESFORMAT_FOREGROUND="$POWERLEVEL9K_VCS_CLEAN_FOREGROUND"
    typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_OUTGOING_CHANGESFORMAT_FOREGROUND="$POWERLEVEL9K_VCS_CLEAN_FOREGROUND"
    typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STASHFORMAT_FOREGROUND="$POWERLEVEL9K_VCS_CLEAN_FOREGROUND"
    typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_ACTIONFORMAT_FOREGROUND="$__PASTEL_COLORS[red]"

    typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED,CONFLICTED,COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=-1

    typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON="?"
    typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON="!"
    typeset -g POWERLEVEL9K_VCS_STAGED_ICON="+"
    typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=">"
    typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON="<"
    typeset -g POWERLEVEL9K_VCS_STASH_ICON="*"
}

_pastel_config_vcs() {
    typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND="$__PASTEL_COLORS[grey]"
    typeset -g POWERLEVEL9K_VCS_LOADING_ACTION_FOREGROUND="$POWERLEVEL9K_VCS_LOADING_FOREGROUND"
    typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND="$__PASTEL_COLORS[brightgreen]"
    typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="$__PASTEL_COLORS[red]"
    typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="$__PASTEL_COLORS[yellow]"
    typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED,LOADING}_BACKGROUND="none"
    
    typeset -g POWERLEVEL9K_VCS_GIT_ICON=""
    typeset -g POWERLEVEL9K_VCS_GIT_GITHUB_ICON=""
    typeset -g POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=""
    typeset -g POWERLEVEL9K_VCS_GIT_GITLAB_ICON=""
    typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=""
    typeset -g POWERLEVEL9K_VCS_COMMIT_ICON=""

    typeset -g POWERLEVEL9K_SHOW_CHANGESET=false
    typeset -g POWERLEVEL9K_CHANGESET_HASH_LENGTH=6

    if typeset -f _pastel_config_vcs_$PASTEL_THEME_MODE > /dev/null; then
            _pastel_config_vcs_$PASTEL_THEME_MODE
    fi
}

_pastel_config_vi_mode() {
    typeset -g POWERLEVEL9K_VI_MODE_BACKGROUND="none"
}

_pastel_config_virtualenv() {
    typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND="$__PASTEL_COLORS[green]"
    typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND="none"
    
    typeset -g POWERLEVEL9K_PYTHON_ICON=""
}
